let S={token:localStorage.token,user:JSON.parse(localStorage.user||"null"),role:"Admin",page:"dashboard",otpEmail:""};
const $=x=>document.getElementById(x); async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(S.token?{Authorization:"Bearer "+S.token}:{})};if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
function toast(x){let e=document.createElement("div");e.className="toast";e.textContent=x;document.body.append(e);setTimeout(()=>e.remove(),2500)}
function login(){document.body.innerHTML=`<div class=login><div class=box><div class=brand>GeoAttend</div><p class=muted>Real-time QR Attendance + Geofencing</p><div class=roles><button class=${S.role==="Admin"?"on":""} onclick="S.role='Admin';login()">Admin</button><button class=${S.role==="Faculty"?"on":""} onclick="S.role='Faculty';login()">Faculty</button></div><label>Email</label><input id=email class=input value="${S.role==="Admin"?"admin@geoattend.demo":"faculty@geoattend.demo"}><br><br><button class="btn primary" style="width:100%" onclick="sendOtp()">Send OTP</button><p class=muted>Demo mode OTP: <b>123456</b></p></div></div>`}
async function sendOtp(){S.otpEmail=$("email").value;try{let d=await api("/api/auth/send-otp",{method:"POST",body:{email:S.otpEmail,role:S.role}});document.querySelector(".box").innerHTML=`<div class=brand>Verify OTP</div><p class=muted>OTP sent to ${S.otpEmail}</p><input id=otp class=input maxlength=6 placeholder="6-digit OTP"><br><br><button class="btn primary" style="width:100%" onclick="verify()">Verify & Login</button><p class=muted>Demo OTP: <b>${d.demoOtp||"sent via provider"}</b></p>`}catch(e){toast(e.message)}}
async function verify(){try{let d=await api("/api/auth/verify-otp",{method:"POST",body:{email:S.otpEmail,otp:$("otp").value}});S.token=d.token;S.user=d.user;localStorage.token=S.token;localStorage.user=JSON.stringify(S.user);render()}catch(e){toast(e.message)}}
function logout(){localStorage.clear();S={token:null,user:null,role:"Admin",page:"dashboard"};login()}
function nav(p){S.page=p;render()}
async function render(){if(!S.token){login();return}document.body.innerHTML=`<header class=top><div class=brand>GeoAttend</div><div class=row><span>${S.user.name}</span><div class=avatar>${S.user.name[0]}</div><button class="btn secondary" onclick=logout()>Logout</button></div></header><div class=layout><aside class=side><div class="nav ${S.page==="dashboard"?"active":""}" onclick="nav('dashboard')">📊 Dashboard</div><div class="nav ${S.page==="sessions"?"active":""}" onclick="nav('sessions')">📷 QR Sessions</div><div class="nav ${S.page==="attendance"?"active":""}" onclick="nav('attendance')">📝 Attendance</div>${S.user.role==="Admin"?`<div class="nav ${S.page==="users"?"active":""}" onclick="nav('users')">👥 Users</div>`:""}</aside><main class=main id=main>Loading...</main></div>`;await page()}
async function page(){let m=$("main");if(S.page==="dashboard"){let a=await api("/api/attendance");m.innerHTML=`<h1 class=title>Welcome back, ${S.user.name.split(" ")[0]} 👋</h1><p class=muted>Live attendance control center</p><div class="grid section"><div class=card><div class=muted>Attendance Today</div><div class=stat>${a.length}</div></div><div class=card><div class=muted>Security</div><div class=stat>QR + GPS</div></div><div class=card><div class=muted>QR Expiry</div><div class=stat>2 min</div></div><div class=card><div class=muted>Geofence</div><div class=stat>100 m</div></div></div><div class="card section"><h3>Recent attendance</h3>${table(a.slice(0,8))}</div>`}else if(S.page==="attendance"){let a=await api("/api/attendance");m.innerHTML=`<h1 class=title>Attendance Records</h1><p class=muted>Every check-in is verified against the session geofence.</p><div class="card section">${table(a)}</div>`}else if(S.page==="users"){let u=await api("/api/users");m.innerHTML=`<div class=row><div><h1 class=title>Users</h1><p class=muted>Manage students and faculty</p></div><button class="btn primary" onclick=addUser()>+ Add User</button></div><div class="card section"><table class=table><tr><th>Name</th><th>Email</th><th>Role</th><th></th></tr>${u.map(x=>`<tr><td>${x.name}</td><td>${x.email}</td><td>${x.role}</td><td>${x.role!=="Admin"?`<button class="btn danger" onclick="delUser(${x.id})">Delete</button>`:"Protected"}</td></tr>`).join("")}</table></div>`}else if(S.page==="sessions"){let s=await api("/api/sessions/active");m.innerHTML=`<div class=row><div><h1 class=title>QR Sessions</h1><p class=muted>Start a live QR attendance window</p></div><button class="btn primary" onclick=startSession>+ Start Session</button></div>${s?`<div class="card section"><h3>${s.course}</h3><img class=qr src="/api/sessions/${s.id}/qr"><p style="text-align:center">Students must be inside <b>${s.radius}m</b> geofence.</p><button class="btn danger" onclick="stopSession(${s.id})">Stop Session</button></div>`:`<div class="card section" style="text-align:center;padding:50px"><h3>No active session</h3><p class=muted>Start a session to generate a live QR code.</p></div>`}`}}
function table(a){return `<table class=table><tr><th>Student</th><th>Course</th><th>Distance</th><th>Time</th><th>Status</th></tr>${a.map(x=>`<tr><td>${x.name}</td><td>${x.course}</td><td>${Math.round(x.distance)}m</td><td>${new Date(x.created_at).toLocaleString()}</td><td><span class="badge green">Present</span></td></tr>`).join("")}</table>`}
async function startSession(){let course=prompt("Course / Class name","CSE-A — Data Structures");if(!course)return;navigator.geolocation.getCurrentPosition(async p=>{try{await api("/api/sessions",{method:"POST",body:{course,lat:p.coords.latitude,lng:p.coords.longitude,radius:100}});toast("Live QR session started");render()}catch(e){toast(e.message)}},()=>toast("Location permission required"))}
async function stopSession(id){await api("/api/sessions/"+id+"/stop",{method:"POST"});toast("Session stopped");render()}
async function addUser(){let name=prompt("Name"),email=prompt("Email"),role=prompt("Role: Student or Faculty","Student");if(!name||!email)return;try{await api("/api/users",{method:"POST",body:{name,email,role}});render()}catch(e){toast(e.message)}}
async function delUser(id){await api("/api/users/"+id,{method:"DELETE"});render()}
render();