const express=require("express"), path=require("path"), Database=require("better-sqlite3"), jwt=require("jsonwebtoken"), QRCode=require("qrcode");
const app=express(), PORT=process.env.PORT||3000, SECRET=process.env.JWT_SECRET||"change-me";
app.use(express.json()); app.use(express.static(path.join(__dirname,"public")));
const db=new Database(path.join(__dirname,"data.sqlite"));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT UNIQUE,role TEXT);
CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,course TEXT,lat REAL,lng REAL,radius REAL,token TEXT,expires INTEGER,active INTEGER DEFAULT 1,created_at TEXT);
CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id INTEGER,user_id INTEGER,lat REAL,lng REAL,distance REAL,created_at TEXT,UNIQUE(session_id,user_id));`);
const count=db.prepare("SELECT COUNT(*) c FROM users").get().c;
if(!count) db.prepare("INSERT INTO users(name,email,role) VALUES (?,?,?),(?,?,?),(?,?,?)").run("Admin User","admin@geoattend.demo","Admin","Dr. Priya","faculty@geoattend.demo","Faculty","Rahul Kumar","rahul@geoattend.demo","Student");
const otpStore=new Map();
function auth(req,res,next){try{const t=(req.headers.authorization||"").replace("Bearer ","");req.user=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({error:"Unauthorized"})}}
function distance(a,b,c,d){const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
app.post("/api/auth/send-otp",(req,res)=>{const {email,role}=req.body||{}; if(!email||!role)return res.status(400).json({error:"Email and role required"});let u=db.prepare("SELECT * FROM users WHERE email=? AND role=?").get(email,role);if(!u){if(role==="Admin")u=db.prepare("SELECT * FROM users WHERE role='Admin' LIMIT 1").get();else if(role==="Faculty")u=db.prepare("SELECT * FROM users WHERE role='Faculty' LIMIT 1").get();} const otp=process.env.OTP_MODE==="production"?String(Math.floor(100000+Math.random()*900000)):"123456";otpStore.set(email,{otp,role,expires:Date.now()+300000,user:u}); console.log("OTP for",email,otp);res.json({message:"OTP sent",demoOtp:process.env.OTP_MODE==="demo"?"123456":undefined})});
app.post("/api/auth/verify-otp",(req,res)=>{const {email,otp}=req.body||{},x=otpStore.get(email);if(!x||x.expires<Date.now()||x.otp!==otp)return res.status(401).json({error:"Invalid or expired OTP"});let u=x.user||db.prepare("SELECT * FROM users WHERE email=?").get(email);if(!u)return res.status(403).json({error:"User not registered"});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},SECRET,{expiresIn:"8h"});otpStore.delete(email);res.json({token,user:u})});
app.get("/api/users",auth,(req,res)=>{if(req.user.role!=="Admin")return res.status(403).json({error:"Admin only"});res.json(db.prepare("SELECT id,name,email,role FROM users ORDER BY id DESC").all())});
app.post("/api/users",auth,(req,res)=>{if(req.user.role!=="Admin")return res.status(403).json({error:"Admin only"});try{const r=db.prepare("INSERT INTO users(name,email,role) VALUES (?,?,?)").run(req.body.name,req.body.email,req.body.role);res.json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:"Email already exists"})}});
app.delete("/api/users/:id",auth,(req,res)=>{if(req.user.role!=="Admin")return res.status(403).json({error:"Admin only"});db.prepare("DELETE FROM users WHERE id=? AND role!='Admin'").run(req.params.id);res.json({ok:true})});
app.post("/api/sessions",auth,(req,res)=>{if(!["Admin","Faculty"].includes(req.user.role))return res.status(403).json({error:"Faculty/Admin only"});const {course,lat,lng,radius=100}=req.body;const token=require("crypto").randomBytes(18).toString("hex"),expires=Date.now()+120000;const r=db.prepare("INSERT INTO sessions(course,lat,lng,radius,token,expires,created_at) VALUES (?,?,?,?,?,?,?)").run(course,lat,lng,radius,token,expires,new Date().toISOString());res.json({id:r.lastInsertRowid,course,expires,qr:`/api/sessions/${r.lastInsertRowid}/qr`})});
app.get("/api/sessions/active",auth,(req,res)=>res.json(db.prepare("SELECT id,course,lat,lng,radius,expires,created_at FROM sessions WHERE active=1 ORDER BY id DESC LIMIT 1").get()||null));
app.get("/api/sessions/:id/qr",async(req,res)=>{const s=db.prepare("SELECT id,token,expires FROM sessions WHERE id=? AND active=1").get(req.params.id);if(!s||s.expires<Date.now())return res.status(410).send("QR expired");res.type("png").send(await QRCode.toBuffer(JSON.stringify({sessionId:s.id,token:s.token,expires:s.expires})))});
app.post("/api/attendance",auth,(req,res)=>{if(req.user.role!=="Student")return res.status(403).json({error:"Student only"});const {sessionId,token,lat,lng}=req.body,s=db.prepare("SELECT * FROM sessions WHERE id=? AND active=1").get(sessionId);if(!s||s.expires<Date.now()||s.token!==token)return res.status(400).json({error:"QR expired or invalid"});const dist=distance(s.lat,s.lng,lat,lng);if(dist>s.radius)return res.status(400).json({error:`Outside geofence (${Math.round(dist)}m away)`});try{db.prepare("INSERT INTO attendance(session_id,user_id,lat,lng,distance,created_at) VALUES (?,?,?,?,?,?)").run(s.id,req.user.id,lat,lng,dist,new Date().toISOString());res.json({ok:true,distance:Math.round(dist)})}catch(e){res.status(409).json({error:"Attendance already marked"})}});
app.get("/api/attendance",auth,(req,res)=>{const q=`SELECT a.id,u.name,u.email,s.course,a.distance,a.created_at FROM attendance a JOIN users u ON u.id=a.user_id JOIN sessions s ON s.id=a.session_id ORDER BY a.id DESC`;res.json(db.prepare(q).all())});
app.post("/api/sessions/:id/stop",auth,(req,res)=>{if(!["Admin","Faculty"].includes(req.user.role))return res.status(403).json({error:"Not allowed"});db.prepare("UPDATE sessions SET active=0 WHERE id=?").run(req.params.id);res.json({ok:true})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("GeoAttend running on "+PORT));